[DEFAULT]
ServerAliveInterval = 45
Compression = yes
#


[SEVERE]
Port = 50022
ForwardX11 = no

[GENERAL]
domains = tourism
seed = 20230301

[logging]
usecolor = False
screen_level = results
file_level = results
file = auto